drop table if exists #test
create table #test (id int identity, sBag varchar(500), sContent varchar(500))

insert into #test values
 ('vibrant bronze', '3 dim olive'), 
 ('shiny teal', '1 posh green, 5 pale indigo, 1 mirrored purple'), 
 ('striped aqua', '5 bright orange'), 
 ('clear chartreuse', '3 dotted black, 2 wavy olive'), 
 ('light lime', '1 posh silver, 5 clear orange, 2 light olive, 3 dull maroon'), 
 ('light olive', '4 striped turquoise'), 
 ('shiny purple', '2 posh silver, 3 striped silver, 5 shiny beige, 2 plaid chartreuse'), 
 ('mirrored crimson', '2 faded cyan'), 
 ('shiny turquoise', '5 dull purple'), 
 ('dim red', '2 dim salmon, 2 faded orange, 5 muted aqua'), 
 ('vibrant yellow', '5 mirrored white, 5 vibrant blue, 3 mirrored lavender, 1 wavy cyan'), 
 ('posh salmon', '1 dull black, 1 striped indigo, 1 muted silver, 2 vibrant crimson'), 
 ('pale black', '1 plaid cyan'), 
 ('dotted salmon', '3 wavy brown, 3 pale coral, 1 light maroon'), 
 ('posh orange', '5 muted green, 3 striped violet'), 
 ('dull maroon', '2 clear brown, 5 posh silver, 5 mirrored coral, 2 dim lavender'), 
 ('bright lavender', '3 dark chartreuse, 1 mirrored chartreuse, 2 striped orange, 4 striped bronze'), 
 ('plaid white', '2 pale aqua'), 
 ('posh teal', '1 muted crimson, 2 dark fuchsia, 2 dim black, 4 plaid cyan'), 
 ('wavy maroon', '2 dull magenta, 3 dark red, 5 dull green, 4 bright turquoise'), 
 ('plaid teal', '5 plaid plum, 3 light magenta'), 
 ('plaid plum', '3 striped lime, 5 clear maroon, 3 muted plum'), 
 ('muted purple', '5 muted fuchsia, 4 pale tomato'), 
 ('dark gold', '5 dim lime, 3 clear orange, 4 drab crimson, 1 faded cyan'), 
 ('striped coral', '4 pale aqua, 5 clear silver'), 
 ('shiny chartreuse', '1 muted plum, 3 vibrant tomato'), 
 ('bright salmon', '5 pale gold, 1 muted gold, 5 dark gray, 4 dull cyan'), 
 ('dark crimson', '1 plaid turquoise'), 
 ('light coral', '1 muted brown, 2 striped black, 5 dark gray'), 
 ('dotted lavender', '1 bright turquoise'), 
 ('posh red', '2 muted green'), 
 ('dim turquoise', '4 dull chartreuse'), 
 ('posh lime', '5 mirrored yellow, 1 striped silver'), 
 ('wavy black', '5 striped cyan, 4 wavy red, 2 dotted coral'), 
 ('dotted brown', '1 dim gray, 1 plaid tomato'), 
 ('mirrored red', '4 posh aqua, 4 dark gray, 5 dark turquoise'), 
 ('plaid tan', '4 plaid black, 4 dull fuchsia, 1 plaid plum, 3 dark chartreuse'), 
 ('plaid bronze', '2 muted lavender, 3 faded cyan, 3 mirrored chartreuse, 1 dull coral'), 
 ('mirrored silver', '3 dull bronze, 3 dim tomato'), 
 ('shiny fuchsia', '3 bright maroon, 1 vibrant tomato, 4 posh bronze, 1 striped bronze'), 
 ('dotted plum', '5 wavy fuchsia'), 
 ('dim bronze', '3 shiny red, 5 dotted chartreuse'), 
 ('faded crimson', '3 bright olive, 1 dark bronze, 5 drab crimson'), 
 ('striped blue', '4 drab blue'), 
 ('posh purple', '1 bright blue, 4 light black, 1 dotted violet'), 
 ('shiny lavender', '4 mirrored bronze'), 
 ('dull beige', '2 wavy chartreuse'), 
 ('dim blue', '1 bright magenta, 5 muted red'), 
 ('pale yellow', '1 dotted white'), 
 ('mirrored blue', '3 striped tan'), 
 ('mirrored turquoise', '2 plaid red, 5 muted red, 2 muted green'), 
 ('faded fuchsia', '3 wavy tomato, 1 vibrant red, 1 dotted green, 2 posh plum'), 
 ('drab silver', '2 muted fuchsia, 4 dotted gray, 4 dotted aqua'), 
 ('clear teal', '5 shiny maroon, 1 clear green'), 
 ('dim brown', '4 faded lavender, 5 striped lime, 1 dark aqua, 1 dark fuchsia'), 
 ('muted beige', '1 dim aqua, 4 plaid plum, 3 light white, 4 muted cyan'), 
 ('muted blue', '2 bright blue'), 
 ('vibrant turquoise', '3 muted crimson'), 
 ('mirrored indigo', '2 wavy lime, 5 bright olive, 5 bright black, 5 vibrant violet'), 
 ('posh tomato', '4 muted orange, 3 plaid white, 3 shiny tomato, 3 light beige'), 
 ('bright gray', '5 pale aqua, 3 shiny gold, 1 clear olive, 1 dull fuchsia'), 
 ('pale green', '4 light black, 3 posh purple, 2 clear chartreuse, 2 drab lime'), 
 ('light orange', '5 shiny chartreuse, 2 wavy blue, 2 wavy yellow'), 
 ('light green', '5 dark bronze, 4 light tan, 4 dim chartreuse'), 
 ('shiny indigo', '3 faded cyan'), 
 ('dotted orange', '2 wavy crimson, 3 dull green, 5 dark indigo'), 
 ('dotted black', '2 vibrant white'), 
 ('plaid gold', '3 mirrored bronze, 5 striped tan'), 
 ('muted salmon', '5 dull maroon, 1 vibrant tan, 1 dim purple, 4 dull chartreuse'), 
 ('plaid salmon', '5 dotted purple, 5 dim orange'), 
 ('bright crimson', '3 plaid maroon, 2 dim aqua, 5 dull magenta, 5 pale tomato'), 
 ('dotted fuchsia', '1 dark cyan, 1 striped magenta, 3 clear coral, 4 light purple'), 
 ('dull blue', '5 dim magenta, 1 mirrored maroon, 5 dark indigo'), 
 ('dull orange', '3 drab blue, 1 shiny beige'), 
 ('muted red', '5 clear brown, 5 striped turquoise, 3 dull fuchsia'), 
 ('shiny coral', '5 dark olive, 5 light blue'), 
 ('drab violet', '5 clear chartreuse, 2 posh orange, 3 pale purple'), 
 ('clear blue', '4 dull fuchsia, 4 faded purple, 3 mirrored plum'), 
 ('vibrant beige', '2 posh silver'), 
 ('bright bronze', '1 shiny yellow, 5 muted green, 3 dark gray'), 
 ('bright orange', 'no other'), 
 ('light teal', '3 mirrored magenta, 5 faded gray'), 
 ('dark green', '4 drab white, 2 drab green, 5 dotted coral, 1 mirrored black'), 
 ('plaid silver', '2 dotted bronze'), 
 ('drab turquoise', '3 bright white, 3 drab maroon'), 
 ('dim magenta', '5 dark fuchsia, 2 drab teal, 2 drab crimson, 2 dull fuchsia'), 
 ('pale coral', 'no other'), 
 ('dull indigo', '2 bright black, 1 drab lime, 5 light magenta, 1 faded orange'), 
 ('dim indigo', '5 dark maroon'), 
 ('shiny gold', '5 light black, 3 mirrored yellow, 5 muted plum'), 
 ('faded lime', '5 dark crimson, 3 shiny orange, 5 plaid tomato, 4 mirrored cyan'), 
 ('faded cyan', '3 shiny gold'), 
 ('striped olive', '4 vibrant red'), 
 ('wavy white', '5 posh silver, 5 mirrored gold, 5 pale black'), 
 ('dim plum', '5 dotted plum, 2 clear silver, 2 wavy bronze'), 
 ('drab cyan', '2 muted plum, 2 dotted bronze, 3 posh violet'), 
 ('clear bronze', '1 clear plum, 5 striped plum'), 
 ('posh gray', '5 clear chartreuse'), 
 ('striped brown', '3 dim olive, 1 light black, 4 vibrant crimson, 2 striped fuchsia'), 
 ('wavy tomato', '2 mirrored chartreuse'), 
 ('dull white', '1 mirrored brown, 2 dull green'), 
 ('vibrant green', '4 drab fuchsia'), 
 ('dark tomato', '3 light gray, 2 dull cyan, 4 striped silver, 5 dark fuchsia'), 
 ('dim tomato', '2 dark turquoise, 1 mirrored black, 3 posh maroon'), 
 ('bright gold', '5 pale aqua, 3 clear tomato, 1 dark yellow, 1 drab green'), 
 ('dotted indigo', '5 light purple, 2 plaid coral, 5 pale green'), 
 ('plaid magenta', '1 dotted bronze, 3 drab turquoise, 1 dark lime'), 
 ('drab gray', '3 dark gray, 5 clear turquoise'), 
 ('dim gold', '5 dark maroon'), 
 ('dark black', '5 dark violet, 2 dotted cyan'), 
 ('posh chartreuse', '2 posh magenta, 2 striped lime'), 
 ('wavy beige', '3 drab olive, 2 shiny beige, 1 faded purple'), 
 ('plaid green', '5 pale olive, 5 posh bronze, 4 bright tomato'), 
 ('dotted blue', '3 posh silver'), 
 ('shiny cyan', '1 mirrored turquoise, 1 striped beige, 5 bright silver, 3 light olive'), 
 ('dark aqua', '1 plaid black, 3 posh coral, 4 striped magenta, 2 mirrored turquoise'), 
 ('drab salmon', '2 striped bronze'), 
 ('posh brown', '3 bright white'), 
 ('mirrored chartreuse', '5 posh lime, 4 bright blue, 4 clear brown, 3 bright orange'), 
 ('clear red', '1 plaid beige, 2 posh brown, 2 shiny aqua'), 
 ('wavy olive', '4 clear maroon, 1 striped silver'), 
 ('faded green', '4 plaid red, 3 dim olive'), 
 ('clear purple', '1 plaid olive, 3 light chartreuse'), 
 ('dull lime', '4 dark tan, 1 light chartreuse, 5 vibrant silver'), 
 ('dark red', '5 faded orange'), 
 ('wavy plum', '5 dull teal, 3 clear maroon, 3 shiny tan'), 
 ('dark white', '3 muted red'), 
 ('light turquoise', '3 light black'), 
 ('pale fuchsia', '3 dim brown, 5 clear purple'), 
 ('light maroon', '3 mirrored turquoise'), 
 ('striped fuchsia', '1 dotted aqua'), 
 ('mirrored magenta', '5 striped white, 4 striped violet, 4 dull maroon, 5 striped indigo'), 
 ('dark violet', '2 mirrored black, 5 dotted fuchsia, 3 muted fuchsia'), 
 ('muted cyan', '3 muted salmon, 4 drab black, 2 posh green'), 
 ('muted tan', '4 posh coral, 2 bright fuchsia'), 
 ('faded aqua', '5 striped magenta, 1 dim aqua'), 
 ('bright tomato', '2 muted green, 1 light olive'), 
 ('clear silver', '4 wavy cyan, 3 bright orange, 5 mirrored coral, 3 light olive'), 
 ('vibrant chartreuse', '4 light gray'), 
 ('dull olive', '1 mirrored lavender, 4 dotted coral, 4 pale chartreuse, 1 dull coral'), 
 ('pale gray', '3 plaid orange'), 
 ('wavy lime', '1 bright orange, 2 wavy yellow, 2 light purple, 4 wavy indigo'), 
 ('faded white', '1 dotted violet, 1 dark maroon, 3 posh coral'), 
 ('muted white', '3 faded magenta'), 
 ('wavy brown', '4 vibrant yellow, 4 dull lavender'), 
 ('clear violet', '5 shiny tan'), 
 ('clear olive', '3 bright fuchsia, 5 dark maroon, 4 mirrored white, 5 shiny beige'), 
 ('light beige', '4 mirrored gray, 2 wavy brown, 3 pale blue, 4 striped silver'), 
 ('plaid turquoise', '1 vibrant aqua, 4 bright fuchsia'), 
 ('posh coral', '3 dark tomato'), 
 ('wavy red', '5 posh gray, 3 dim lime, 2 light tan, 3 bright blue'), 
 ('wavy fuchsia', '5 vibrant aqua'), 
 ('faded turquoise', '2 dark maroon, 1 pale indigo, 4 faded white'), 
 ('clear indigo', '4 pale purple, 5 dull green, 1 bright olive'), 
 ('vibrant lime', '1 light purple, 5 posh bronze, 5 drab blue, 1 bright black'), 
 ('shiny bronze', '1 plaid red'), 
 ('vibrant plum', '1 wavy black, 4 drab aqua, 5 dark cyan'), 
 ('mirrored fuchsia', '5 bright olive, 4 mirrored crimson, 1 dim salmon'), 
 ('bright fuchsia', '4 light gray'), 
 ('bright silver', '5 striped tan'), 
 ('dotted gray', '1 striped silver, 5 bright black, 2 mirrored yellow'), 
 ('dark olive', '5 striped lime, 1 bright black'), 
 ('light lavender', '1 dark bronze, 2 faded gold, 3 light orange'), 
 ('mirrored green', '2 faded orange'), 
 ('faded blue', '2 drab coral, 3 posh salmon'), 
 ('vibrant red', '3 bright cyan, 4 light aqua, 4 posh gray, 5 wavy purple'), 
 ('dotted yellow', '3 mirrored tan, 1 clear crimson, 3 light turquoise'), 
 ('clear orange', '4 pale coral, 3 posh silver, 2 dull fuchsia'), 
 ('pale violet', '5 light crimson'), 
 ('mirrored beige', '5 bright coral'), 
 ('shiny tomato', '4 dotted red, 2 plaid lavender, 5 dim orange'), 
 ('muted bronze', '3 striped tan, 3 faded orange, 2 faded maroon, 3 clear tomato'), 
 ('muted fuchsia', '1 dark maroon, 2 dotted bronze, 4 mirrored bronze, 1 faded cyan'), 
 ('mirrored orange', '2 plaid cyan, 5 wavy orange, 5 shiny aqua, 5 wavy tan'), 
 ('light blue', '1 mirrored chartreuse, 3 dim crimson'), 
 ('bright turquoise', '2 clear orange'), 
 ('dark plum', '3 wavy lime, 1 light tan, 3 light silver, 1 light lime'), 
 ('wavy cyan', '4 dull coral, 4 light olive'), 
 ('striped cyan', '4 dull lavender'), 
 ('drab purple', '4 shiny tomato, 4 bright orange, 4 mirrored gold'), 
 ('faded indigo', '5 mirrored indigo, 2 muted silver, 5 faded lime, 4 dim salmon'), 
 ('faded orange', '5 plaid chartreuse, 4 bright black, 5 light magenta, 4 wavy bronze'), 
 ('wavy gold', '1 shiny orange, 3 clear salmon, 3 plaid orange, 4 vibrant tan'), 
 ('wavy blue', '3 clear brown, 1 faded tomato, 5 drab green'), 
 ('plaid violet', '1 light blue, 5 drab purple'), 
 ('wavy tan', '4 dotted blue'), 
 ('drab plum', '2 muted silver, 5 shiny maroon'), 
 ('drab fuchsia', '2 muted maroon, 2 mirrored turquoise, 5 clear green, 3 light olive'), 
 ('light violet', '4 clear turquoise, 4 mirrored gold, 2 wavy chartreuse, 2 mirrored tan'), 
 ('shiny maroon', '1 plaid salmon, 4 pale brown, 1 dim orange, 1 wavy tomato'), 
 ('drab crimson', '2 dim gray, 5 dull fuchsia'), 
 ('faded plum', '2 striped turquoise, 5 light gray'), 
 ('clear beige', '4 faded orange, 2 mirrored black, 1 shiny red, 1 dark teal'), 
 ('faded black', '5 mirrored plum, 5 muted plum'), 
 ('pale olive', '4 muted yellow, 5 mirrored maroon'), 
 ('plaid black', '3 dark gray'), 
 ('plaid fuchsia', '1 wavy beige'), 
 ('shiny white', '3 posh orange, 5 posh blue, 4 faded white, 1 wavy crimson'), 
 ('shiny lime', '5 posh black, 2 mirrored bronze, 5 muted bronze, 2 posh violet'), 
 ('shiny magenta', '5 dark lime'), 
 ('plaid tomato', '5 wavy cyan, 3 clear brown, 3 dark olive, 4 vibrant white'), 
 ('dark blue', '3 mirrored black, 3 pale indigo, 3 dim cyan, 3 light olive'), 
 ('muted lavender', '1 dotted purple, 1 drab blue, 5 mirrored bronze, 3 striped violet'), 
 ('faded silver', '2 dim orange, 4 shiny chartreuse, 2 drab blue, 1 wavy violet'), 
 ('shiny beige', '4 muted green, 5 striped aqua, 2 dim black, 3 dull fuchsia'), 
 ('vibrant indigo', '3 pale red, 3 clear lime, 4 vibrant cyan, 2 pale tomato'), 
 ('bright red', '2 mirrored lime, 1 dim indigo, 5 bright black, 2 drab crimson'), 
 ('light gray', 'no other'), 
 ('dim orange', '4 clear chartreuse, 4 striped tan'), 
 ('dull plum', '4 faded aqua, 3 pale salmon, 1 posh gray'), 
 ('dull crimson', '5 posh red, 4 mirrored plum, 1 dull fuchsia'), 
 ('pale blue', '1 dotted red, 5 muted chartreuse, 3 clear green, 1 wavy beige'), 
 ('dotted cyan', '4 faded red, 2 bright gold'), 
 ('mirrored lavender', '1 vibrant white, 1 mirrored plum, 5 dotted black, 5 bright orange'), 
 ('mirrored tomato', '2 shiny chartreuse, 2 shiny bronze, 4 bright turquoise'), 
 ('bright indigo', '3 striped orange, 1 dotted lime, 1 shiny magenta, 2 light fuchsia'), 
 ('drab brown', '5 plaid magenta, 5 dim aqua, 4 vibrant aqua'), 
 ('posh turquoise', '3 bright tomato, 4 striped tomato, 5 dim turquoise'), 
 ('shiny violet', '1 drab gold, 5 plaid silver, 3 vibrant magenta'), 
 ('bright green', '5 dull aqua, 2 pale tomato, 1 posh lavender, 1 dim tomato'), 
 ('striped tomato', '4 bright salmon'), 
 ('shiny black', '3 drab aqua, 4 drab salmon, 1 dim turquoise'), 
 ('dotted silver', '4 plaid orange, 3 mirrored tan'), 
 ('shiny red', '4 dim lime, 3 posh bronze, 3 striped tomato, 2 vibrant aqua'), 
 ('dim green', '3 dotted blue, 4 faded cyan, 4 drab silver, 5 clear blue'), 
 ('dull teal', '4 striped orange, 5 bright coral, 4 bright gold'), 
 ('posh beige', '4 dark indigo'), 
 ('clear green', '3 drab blue, 2 dark maroon'), 
 ('faded teal', '4 mirrored maroon, 3 clear cyan, 4 plaid silver'), 
 ('plaid maroon', '2 plaid brown'), 
 ('light yellow', '3 dotted chartreuse'), 
 ('dotted green', '1 clear olive, 2 bright blue, 3 striped indigo, 3 dull indigo'), 
 ('vibrant lavender', '4 clear tomato, 1 posh tomato, 4 drab bronze'), 
 ('dull red', '1 dark red, 4 bright black'), 
 ('dark chartreuse', '2 clear turquoise, 2 clear coral, 2 vibrant magenta'), 
 ('clear aqua', '3 mirrored lime'), 
 ('posh white', '4 mirrored chartreuse, 1 light purple, 3 muted maroon, 2 pale olive'), 
 ('pale cyan', '3 plaid lime, 1 drab salmon'), 
 ('mirrored yellow', '4 light olive'), 
 ('faded violet', '2 muted red, 1 striped coral, 1 dark chartreuse, 3 vibrant aqua'), 
 ('bright lime', '1 muted chartreuse'), 
 ('dotted teal', '3 dark orange'), 
 ('plaid beige', '4 drab chartreuse, 5 clear orange, 1 dim orange, 4 dotted bronze'), 
 ('muted violet', '5 striped crimson, 3 dark gold, 4 muted magenta, 5 vibrant olive'), 
 ('dotted turquoise', '1 drab olive, 1 plaid turquoise'), 
 ('dim yellow', '4 dotted blue, 4 wavy teal'), 
 ('light purple', '1 mirrored yellow'), 
 ('wavy turquoise', '4 muted gold, 3 wavy orange, 3 clear tomato, 1 light tan'), 
 ('vibrant silver', '1 plaid red, 2 clear turquoise'), 
 ('faded brown', '5 faded gray, 3 drab maroon, 5 striped aqua'), 
 ('posh indigo', '1 wavy green, 5 dotted blue'), 
 ('drab lavender', '3 vibrant indigo, 2 faded black, 4 dull coral, 2 wavy lime'), 
 ('vibrant blue', '5 posh purple, 4 dark gold, 2 mirrored lavender'), 
 ('posh blue', '4 wavy bronze, 5 dull chartreuse, 1 muted teal, 3 bright black'), 
 ('posh aqua', '4 pale gold, 2 faded white'), 
 ('bright yellow', '1 wavy coral, 2 drab turquoise'), 
 ('wavy lavender', '2 faded red, 4 faded cyan'), 
 ('dotted aqua', '1 muted cyan, 2 muted black, 3 wavy chartreuse, 1 shiny magenta'), 
 ('vibrant white', '3 muted green, 2 bright tomato'), 
 ('posh yellow', '3 mirrored lime, 5 dark fuchsia, 1 posh red, 5 plaid cyan'), 
 ('clear gray', '4 wavy magenta, 3 shiny orange'), 
 ('clear fuchsia', '2 dull beige, 5 striped turquoise, 2 posh silver'), 
 ('shiny tan', '1 drab orange, 4 faded cyan, 5 dark teal'), 
 ('faded bronze', '2 shiny aqua'), 
 ('pale indigo', '1 plaid turquoise'), 
 ('faded tomato', '3 pale brown'), 
 ('plaid indigo', '1 dull beige'), 
 ('dark salmon', '3 wavy purple, 3 dull indigo, 4 dim blue, 3 dull green'), 
 ('bright tan', '2 posh bronze'), 
 ('vibrant fuchsia', '4 striped olive, 5 clear yellow, 5 muted fuchsia, 3 shiny plum'), 
 ('dark gray', '3 light gray'), 
 ('posh magenta', '5 bright blue'), 
 ('mirrored bronze', '5 bright olive, 4 light magenta'), 
 ('posh cyan', '4 light indigo, 2 dark aqua, 5 mirrored lime, 2 faded magenta'), 
 ('light chartreuse', '4 dark indigo, 2 wavy magenta, 5 dim white, 1 plaid bronze'), 
 ('bright plum', '4 dotted lime, 2 mirrored red, 1 plaid plum, 1 mirrored gold'), 
 ('dark beige', '4 mirrored white, 2 muted plum, 5 mirrored lime, 2 plaid teal'), 
 ('light bronze', '1 muted black'), 
 ('bright magenta', '3 striped lime'), 
 ('dull green', '2 light purple, 1 dull maroon, 2 dotted violet, 4 clear blue'), 
 ('drab maroon', '3 bright tomato'), 
 ('muted gray', '1 shiny plum, 2 posh fuchsia, 1 plaid black, 2 dim black'), 
 ('pale aqua', '5 mirrored plum, 1 dark fuchsia, 3 faded tomato, 1 striped aqua'), 
 ('plaid yellow', '2 plaid plum'), 
 ('vibrant tan', '3 light gray, 5 bright salmon, 3 pale green, 5 posh gray'), 
 ('faded lavender', '2 shiny yellow, 3 dotted black, 4 dotted purple'), 
 ('muted aqua', '3 mirrored blue, 2 plaid salmon'), 
 ('wavy silver', '3 posh lime, 2 striped tan'), 
 ('pale lime', '5 striped orange, 4 plaid turquoise, 1 dark lime, 5 muted cyan'), 
 ('dark bronze', '3 clear silver, 5 faded tomato, 5 light olive, 4 bright fuchsia'), 
 ('dull gray', '1 clear silver, 1 light purple'), 
 ('clear tomato', '3 wavy coral, 2 dim orange, 2 dim magenta'), 
 ('dull chartreuse', '2 plaid teal, 4 dotted purple, 1 faded tomato'), 
 ('vibrant gold', '2 striped aqua, 5 vibrant cyan, 2 dotted olive, 2 clear olive'), 
 ('wavy green', '5 dim lavender'), 
 ('posh olive', '3 striped blue, 4 striped beige, 4 dim violet, 4 muted blue'), 
 ('vibrant brown', '5 light purple, 1 bright orange'), 
 ('faded yellow', '2 dark salmon'), 
 ('vibrant teal', '5 vibrant brown, 5 shiny indigo'), 
 ('drab black', '4 bright magenta, 1 shiny green'), 
 ('mirrored black', '3 posh silver'), 
 ('muted yellow', '1 clear orange, 2 shiny gold, 4 wavy purple'), 
 ('posh silver', 'no other'), 
 ('plaid coral', '2 mirrored lavender, 5 drab lime, 4 pale brown, 4 dark maroon'), 
 ('muted plum', 'no other'), 
 ('pale silver', '2 dim brown, 1 light aqua, 4 shiny lavender'), 
 ('dotted coral', '2 dotted bronze, 1 clear violet, 1 vibrant magenta'), 
 ('drab indigo', '1 dotted crimson'), 
 ('dim salmon', '2 clear green, 4 muted chartreuse'), 
 ('vibrant cyan', '4 posh magenta, 4 clear violet'), 
 ('muted olive', '5 bright salmon, 2 dark silver'), 
 ('drab blue', '2 shiny yellow, 5 clear olive'), 
 ('dark brown', '3 muted cyan, 5 posh fuchsia'), 
 ('dotted red', '3 posh gray, 5 clear maroon, 3 posh fuchsia, 1 dark white'), 
 ('light crimson', '2 dark chartreuse'), 
 ('wavy chartreuse', '1 muted red, 5 dull chartreuse, 2 wavy bronze, 1 posh bronze'), 
 ('plaid lime', '3 pale white, 2 dull chartreuse, 3 plaid olive, 1 vibrant cyan'), 
 ('striped gray', '5 mirrored blue, 3 dark turquoise, 2 clear aqua, 5 drab cyan'), 
 ('dull cyan', 'no other'), 
 ('dotted beige', '5 dull cyan, 2 dull purple, 4 mirrored white, 3 vibrant olive'), 
 ('pale turquoise', '5 pale beige, 2 pale olive, 2 wavy coral, 5 light fuchsia'), 
 ('muted tomato', '1 vibrant olive, 1 bright purple, 3 pale turquoise, 3 striped coral'), 
 ('pale white', '4 dull gold, 5 wavy olive, 4 faded red, 2 plaid teal'), 
 ('clear magenta', '4 dark violet, 5 plaid chartreuse, 3 vibrant yellow'), 
 ('vibrant tomato', '2 posh lime, 4 drab orange, 1 striped turquoise'), 
 ('striped green', '1 dim purple, 3 dotted bronze, 4 bright bronze'), 
 ('wavy salmon', '1 shiny lime'), 
 ('plaid purple', '1 muted tomato, 2 shiny lavender, 5 light olive'), 
 ('clear tan', '2 striped plum, 1 striped fuchsia'), 
 ('dull coral', '5 bright orange, 5 faded purple, 5 plaid chartreuse, 3 muted green'), 
 ('light tomato', '4 faded tomato, 1 clear chartreuse, 2 plaid black, 2 posh plum'), 
 ('dotted lime', '3 bright lavender'), 
 ('plaid blue', '4 plaid black'), 
 ('dull silver', '1 wavy magenta, 2 mirrored fuchsia, 4 striped salmon'), 
 ('dotted maroon', '3 dull cyan, 5 plaid lavender, 3 bright gray'), 
 ('bright black', '4 mirrored plum, 2 drab blue, 3 light gray, 1 posh coral'), 
 ('pale salmon', '5 bright gray'), 
 ('muted chartreuse', '1 mirrored lavender'), 
 ('pale lavender', '4 dim black'), 
 ('dull fuchsia', '1 bright olive, 3 dull cyan, 3 bright tomato'), 
 ('posh fuchsia', '4 striped cyan, 1 shiny purple, 5 muted lavender'), 
 ('dull tan', '2 light magenta'), 
 ('mirrored olive', '5 clear maroon, 3 bright cyan, 2 vibrant plum'), 
 ('plaid chartreuse', '2 pale coral, 1 posh lime, 5 light olive, 2 bright orange'), 
 ('muted teal', '3 plaid teal'), 
 ('dim violet', '3 striped tomato, 1 dotted fuchsia'), 
 ('striped yellow', '2 mirrored brown, 3 faded cyan, 1 clear silver, 5 wavy orange'), 
 ('faded salmon', '5 striped coral'), 
 ('striped turquoise', 'no other'), 
 ('dim white', '5 clear coral'), 
 ('dull violet', '4 striped violet, 5 dotted olive, 4 pale gold, 2 vibrant olive'), 
 ('posh plum', '2 bright orange, 5 faded tomato, 3 pale brown, 1 posh silver'), 
 ('wavy orange', '3 dull maroon, 1 drab orange, 4 posh plum'), 
 ('dotted purple', '2 mirrored white'), 
 ('dark indigo', '3 muted green, 5 dark white, 4 drab olive, 5 vibrant tomato'), 
 ('shiny silver', '2 pale green'), 
 ('shiny crimson', '3 wavy chartreuse, 2 wavy olive'), 
 ('dull salmon', '5 plaid plum'), 
 ('bright brown', '4 clear tan'), 
 ('wavy aqua', '1 dotted tan, 4 bright turquoise, 1 wavy maroon, 4 shiny cyan'), 
 ('mirrored cyan', '1 pale green, 5 plaid chartreuse, 5 muted chartreuse, 1 faded purple'), 
 ('dark yellow', '5 mirrored crimson, 2 shiny beige, 5 mirrored brown, 4 muted aqua'), 
 ('faded gray', '5 wavy cyan, 2 dim olive, 5 wavy gray'), 
 ('drab aqua', '3 shiny purple, 2 dim gray, 3 wavy cyan'), 
 ('vibrant salmon', '2 light indigo, 4 pale maroon'), 
 ('drab yellow', '1 light purple, 5 muted fuchsia, 2 drab blue, 4 muted green'), 
 ('dark maroon', '4 posh coral'), 
 ('drab orange', '4 bright tomato, 4 faded purple, 5 pale brown'), 
 ('dim teal', '4 shiny gray'), 
 ('dotted bronze', '2 drab blue, 1 light magenta'), 
 ('faded maroon', '5 wavy cyan, 1 pale gold'), 
 ('vibrant gray', '3 dull coral, 4 faded lime, 3 mirrored turquoise'), 
 ('wavy yellow', '3 striped bronze'), 
 ('mirrored white', 'no other'), 
 ('pale chartreuse', '5 drab blue, 3 bright black, 1 mirrored lavender, 4 dotted magenta'), 
 ('posh crimson', '1 mirrored lavender, 1 clear cyan'), 
 ('dim coral', '2 posh brown'), 
 ('striped crimson', '3 dim gray, 1 light turquoise, 3 wavy bronze, 4 faded orange'), 
 ('posh violet', '1 dark teal, 4 posh red, 3 vibrant lime'), 
 ('light salmon', '3 plaid salmon'), 
 ('plaid red', '2 dull lavender, 1 posh plum, 4 faded cyan, 1 plaid turquoise'), 
 ('pale maroon', '1 plaid turquoise, 4 faded maroon, 4 shiny yellow, 1 pale purple'), 
 ('striped magenta', '2 posh turquoise, 5 wavy indigo, 4 plaid tomato, 3 dim lavender'), 
 ('striped silver', 'no other'), 
 ('striped gold', '5 bright brown, 1 dotted crimson, 2 bright olive'), 
 ('clear turquoise', '3 wavy teal, 2 muted red'), 
 ('mirrored tan', '5 dark yellow, 3 posh coral'), 
 ('shiny blue', '2 dull olive, 2 muted brown'), 
 ('clear black', '2 wavy teal, 5 plaid chartreuse, 4 dull coral, 5 dark yellow'), 
 ('faded gold', '5 muted teal, 3 bright white, 4 striped tan'), 
 ('drab tan', '1 faded black, 2 clear olive'), 
 ('dark cyan', '1 plaid black, 1 muted aqua, 5 bright fuchsia'), 
 ('muted silver', '1 clear olive, 5 striped indigo'), 
 ('dim beige', '1 muted tomato, 5 clear fuchsia, 1 faded coral'), 
 ('striped red', '3 plaid brown, 4 posh black, 2 dotted gray'), 
 ('striped purple', '5 light lavender, 2 dotted brown, 1 dull olive, 2 shiny aqua'), 
 ('shiny orange', '3 mirrored brown, 1 wavy bronze, 5 vibrant aqua'), 
 ('striped salmon', '4 bright silver'), 
 ('shiny olive', '4 pale gold, 5 drab indigo, 3 mirrored salmon, 2 muted gray'), 
 ('pale bronze', '3 clear cyan, 3 drab blue, 5 drab bronze, 4 shiny gray'), 
 ('plaid aqua', '5 pale yellow, 4 pale black, 3 muted red'), 
 ('faded coral', '3 dark bronze, 5 striped silver, 5 clear olive, 2 wavy gray'), 
 ('striped bronze', '4 posh orange'), 
 ('bright violet', '5 light white, 1 dull olive, 5 drab fuchsia, 3 dim chartreuse'), 
 ('wavy bronze', '2 dark tomato, 2 muted red, 1 drab orange'), 
 ('pale beige', '5 muted lavender, 1 vibrant aqua, 4 drab lime'), 
 ('dim crimson', '4 plaid plum'), 
 ('light silver', '3 shiny yellow, 4 dull fuchsia, 4 dark chartreuse, 1 bright orange'), 
 ('dark coral', '1 clear indigo, 1 muted gold, 5 pale lime'), 
 ('striped plum', '5 plaid white, 3 pale gold, 3 pale yellow, 2 dim orange'), 
 ('light tan', '5 dark crimson, 1 clear silver, 2 striped tomato, 1 vibrant magenta'), 
 ('shiny brown', '4 bright bronze'), 
 ('faded red', '2 dotted bronze'), 
 ('dim gray', '1 pale gold, 5 shiny orange'), 
 ('mirrored plum', '2 muted plum, 1 posh silver'), 
 ('shiny yellow', '4 faded black, 4 light olive'), 
 ('posh bronze', '3 posh orange'), 
 ('clear lime', '5 mirrored lavender, 1 dark tomato, 4 dim aqua, 1 pale purple'), 
 ('drab red', '3 dark tan, 2 shiny maroon, 2 mirrored purple, 5 dotted orange'), 
 ('dull purple', '1 striped yellow, 3 faded cyan, 5 pale red, 4 plaid green'), 
 ('muted magenta', '1 drab yellow, 1 dark lavender'), 
 ('dim fuchsia', '4 pale aqua, 3 mirrored indigo, 2 wavy lime'), 
 ('muted black', '3 bright turquoise, 3 plaid cyan, 5 dim cyan'), 
 ('dark lime', '1 posh orange'), 
 ('drab bronze', '1 pale tomato, 4 light purple, 1 light olive, 4 posh silver'), 
 ('posh tan', '5 bright gold'), 
 ('dim lavender', '1 mirrored white, 4 posh lime, 3 dark fuchsia'), 
 ('dark fuchsia', 'no other'), 
 ('muted maroon', '2 bright white, 4 dark salmon, 4 posh gray, 4 posh plum'), 
 ('dotted crimson', '2 plaid salmon'), 
 ('drab olive', '2 dull lavender, 3 dark tomato'), 
 ('wavy crimson', '3 clear orange, 5 dull maroon'), 
 ('dark silver', '1 muted red, 5 dim bronze'), 
 ('dull magenta', '2 mirrored cyan, 2 mirrored plum, 1 drab olive'), 
 ('pale magenta', '4 dark olive, 1 wavy teal'), 
 ('plaid crimson', '1 dim purple, 1 shiny gold, 5 shiny tan, 2 striped silver'), 
 ('vibrant magenta', '3 striped turquoise'), 
 ('light brown', '2 clear magenta, 2 light lime'), 
 ('drab lime', '2 striped aqua'), 
 ('light aqua', '2 dim orange, 5 mirrored brown, 4 vibrant tomato'), 
 ('dotted white', '3 faded plum, 1 striped lime'), 
 ('muted orange', '4 clear purple, 5 light indigo, 1 plaid bronze'), 
 ('dark turquoise', '2 clear cyan'), 
 ('striped beige', '3 wavy yellow, 2 clear brown, 1 faded plum, 2 dotted bronze'), 
 ('bright chartreuse', '2 dim cyan, 2 faded lavender, 3 muted yellow, 1 dotted turquoise'), 
 ('bright beige', '3 vibrant silver, 3 faded bronze, 4 bright lime, 5 plaid lavender'), 
 ('pale orange', '1 striped tomato, 3 pale brown, 5 plaid bronze, 4 dark salmon'), 
 ('dim black', '4 striped turquoise, 2 plaid chartreuse, 5 posh red, 1 bright tomato'), 
 ('plaid olive', '5 dark indigo, 1 dark teal'), 
 ('plaid orange', '5 muted plum, 4 dark tomato, 5 dull crimson'), 
 ('dark purple', '3 pale beige, 4 pale gold, 1 vibrant blue'), 
 ('mirrored salmon', '3 plaid red, 3 dark plum'), 
 ('vibrant aqua', '3 clear maroon, 1 striped silver, 5 shiny gold, 3 faded tomato'), 
 ('dull lavender', '3 faded white, 1 dim lavender, 2 dull fuchsia'), 
 ('posh green', '5 dim orange'), 
 ('clear salmon', '4 bright black, 5 dotted plum, 2 striped tomato'), 
 ('mirrored violet', '2 wavy black, 5 dotted gold, 3 posh brown'), 
 ('faded magenta', '2 vibrant crimson, 5 drab orange, 1 dark gray, 4 striped coral'), 
 ('light plum', '4 muted plum'), 
 ('dotted tan', '1 wavy gray'), 
 ('dim tan', '5 mirrored bronze, 3 drab olive, 2 wavy olive, 3 dark tan'), 
 ('striped indigo', '2 drab green, 1 light olive, 5 bright orange'), 
 ('vibrant orange', '4 dull fuchsia, 1 shiny violet'), 
 ('dim lime', '5 striped silver'), 
 ('plaid gray', '4 dark tan, 3 dark magenta, 2 drab black, 3 faded bronze'), 
 ('faded chartreuse', '2 clear beige, 2 light beige'), 
 ('striped orange', '5 mirrored coral, 4 light gray, 2 mirrored white'), 
 ('dim silver', '3 posh coral, 4 dotted bronze, 4 muted yellow, 1 faded gray'), 
 ('dotted gold', '1 posh gray'), 
 ('dotted olive', '5 faded aqua, 4 faded brown, 2 dim salmon'), 
 ('posh maroon', '4 striped aqua, 1 wavy yellow, 1 mirrored crimson'), 
 ('dark orange', '3 mirrored fuchsia, 1 light magenta, 2 muted bronze, 2 wavy blue'), 
 ('pale purple', '4 dotted blue'), 
 ('muted indigo', '1 dark fuchsia, 2 posh fuchsia, 5 plaid turquoise, 2 mirrored cyan'), 
 ('faded tan', '1 drab fuchsia, 3 dark beige'), 
 ('bright cyan', '3 dotted blue, 5 muted plum, 2 vibrant crimson, 3 dark gold'), 
 ('mirrored gray', '3 pale lavender, 2 shiny blue, 4 dark salmon'), 
 ('dotted violet', '4 posh red, 4 bright tomato, 3 muted plum'), 
 ('pale tan', '2 clear crimson, 4 drab lime'), 
 ('dull tomato', '2 drab green, 5 dark crimson'), 
 ('wavy coral', '3 light aqua, 3 bright blue, 1 posh gray'), 
 ('dull aqua', '4 drab brown'), 
 ('clear white', '5 dark indigo, 5 dark maroon, 1 striped orange, 2 shiny gold'), 
 ('dotted magenta', '3 light olive, 4 dark indigo, 3 dotted blue, 3 striped lime'), 
 ('plaid cyan', '3 wavy olive, 5 dim black, 4 dotted bronze, 2 striped tomato'), 
 ('muted lime', '3 pale turquoise, 1 posh white'), 
 ('wavy teal', '2 dim orange'), 
 ('muted gold', '1 pale aqua, 4 shiny beige, 2 light olive'), 
 ('wavy magenta', '2 wavy purple, 5 wavy tomato'), 
 ('dim maroon', '5 plaid red'), 
 ('drab green', '5 light gray, 4 clear maroon, 2 dark indigo'), 
 ('plaid lavender', '5 drab blue'), 
 ('light white', '4 light tan'), 
 ('wavy gray', '1 posh coral'), 
 ('mirrored teal', '5 clear brown, 4 bright magenta, 1 drab brown, 2 dull gold'), 
 ('light black', '1 posh coral, 4 dotted black, 4 posh lime, 4 bright blue'), 
 ('shiny gray', '2 dotted blue, 5 striped turquoise, 4 pale aqua, 1 dim black'), 
 ('posh lavender', '1 wavy yellow, 2 dotted tan, 3 dull lavender'), 
 ('faded beige', '5 posh brown, 1 vibrant indigo, 2 light cyan, 1 clear aqua'), 
 ('clear lavender', '1 dull salmon'), 
 ('mirrored coral', '2 light olive, 5 clear olive, 2 pale tomato'), 
 ('bright white', '5 wavy yellow, 5 wavy bronze, 1 wavy olive, 5 muted red'), 
 ('dark lavender', '5 pale tomato, 4 faded white'), 
 ('light red', '3 posh turquoise, 3 dull indigo, 3 wavy silver, 2 drab salmon'), 
 ('vibrant violet', '1 shiny orange'), 
 ('clear gold', '1 drab magenta, 4 plaid tan, 2 vibrant yellow'), 
 ('striped white', '5 light salmon, 1 mirrored purple'), 
 ('vibrant maroon', '4 striped coral'), 
 ('bright olive', '2 light gray, 1 posh silver, 2 bright orange, 1 dark fuchsia'), 
 ('mirrored gold', '1 drab black'), 
 ('shiny green', '4 posh purple'), 
 ('dim aqua', '4 pale gold, 1 dull coral, 3 faded teal, 2 pale yellow'), 
 ('dotted tomato', '4 dull salmon'), 
 ('faded olive', '5 muted green, 1 drab crimson'), 
 ('striped teal', '4 dotted green, 5 muted aqua'), 
 ('pale crimson', '1 striped lime, 4 mirrored tan, 2 clear lavender'), 
 ('shiny salmon', '2 muted salmon, 5 shiny cyan, 4 faded red, 5 light tan'), 
 ('plaid brown', '5 pale orange'), 
 ('posh gold', '3 shiny crimson'), 
 ('wavy violet', '5 muted olive'), 
 ('drab white', '3 posh brown, 2 striped cyan, 1 clear coral'), 
 ('light magenta', '2 clear maroon, 3 light gray, 2 dotted black, 4 bright fuchsia'), 
 ('bright aqua', '4 plaid cyan, 2 clear black'), 
 ('muted green', '5 striped silver, 5 bright orange'), 
 ('dim cyan', '5 plaid brown, 3 striped tan'), 
 ('vibrant olive', '5 dark yellow'), 
 ('dark tan', '1 muted lavender, 2 mirrored turquoise, 1 dim lime, 1 dull olive'), 
 ('mirrored brown', '3 pale brown'), 
 ('mirrored aqua', '1 mirrored plum, 3 dark maroon'), 
 ('clear cyan', '1 dull cyan, 2 dark tomato, 4 pale brown'), 
 ('dull yellow', '4 wavy coral, 4 striped tan, 3 muted chartreuse'), 
 ('mirrored maroon', '3 plaid tomato, 4 shiny purple, 1 plaid lavender, 5 light gray'), 
 ('drab coral', '2 dark turquoise, 2 clear crimson, 4 drab lime, 5 dull crimson'), 
 ('muted turquoise', '5 posh purple, 2 dim magenta'), 
 ('dull turquoise', '4 striped aqua, 2 light fuchsia, 3 pale turquoise, 2 faded maroon'), 
 ('bright maroon', '1 muted red, 3 faded black'), 
 ('wavy indigo', '3 shiny beige, 5 dim lavender, 2 striped tan'), 
 ('pale red', '1 vibrant brown, 3 faded black, 4 posh turquoise, 5 plaid brown'), 
 ('drab teal', '1 faded purple, 2 mirrored blue, 2 vibrant tomato, 1 pale purple'), 
 ('faded purple', '1 vibrant white'), 
 ('striped maroon', '1 mirrored brown, 1 shiny black, 5 dotted lime'), 
 ('dotted chartreuse', '3 dim blue'), 
 ('posh black', '3 light aqua, 5 bright orange, 1 plaid plum, 5 plaid fuchsia'), 
 ('pale gold', '1 faded tomato, 2 dark tomato, 3 dotted blue'), 
 ('muted brown', '1 plaid brown'), 
 ('vibrant purple', '1 shiny gray, 5 dull green'), 
 ('mirrored purple', '1 bright gray, 2 plaid plum, 5 dotted chartreuse, 2 posh lime'), 
 ('bright coral', '3 dim blue'), 
 ('dark magenta', '4 muted maroon, 2 dark olive, 1 dull olive'), 
 ('pale brown', '2 faded purple, 1 muted green, 3 dark fuchsia'), 
 ('drab gold', '3 posh bronze, 2 plaid tomato'), 
 ('pale teal', '1 clear turquoise, 4 muted yellow, 1 posh tomato, 3 vibrant orange'), 
 ('vibrant black', '1 faded tomato, 5 dim white, 2 drab aqua, 1 vibrant silver'), 
 ('dull black', '3 pale yellow, 4 clear aqua, 1 shiny yellow, 3 faded maroon'), 
 ('drab tomato', '2 dim purple, 5 plaid fuchsia'), 
 ('bright blue', '5 posh silver, 4 dull cyan, 4 light olive, 1 mirrored white'), 
 ('muted crimson', '3 bright orange, 1 pale tomato, 3 posh yellow, 4 shiny purple'), 
 ('shiny plum', '1 dim turquoise'), 
 ('clear maroon', '1 posh red, 2 light olive, 1 dotted purple'), 
 ('drab chartreuse', '4 dotted green, 1 dark red'), 
 ('dull brown', '5 dim lavender, 4 bright tomato, 5 drab crimson, 1 vibrant tomato'), 
 ('wavy purple', '4 dim lavender, 2 plaid plum, 2 dim lime, 2 striped cyan'), 
 ('vibrant coral', '1 striped crimson, 3 drab cyan, 5 vibrant yellow, 2 dotted teal'), 
 ('clear crimson', '4 dotted purple, 5 faded cyan'), 
 ('clear coral', '4 clear chartreuse, 2 bright olive'), 
 ('light cyan', '3 shiny violet, 3 dotted blue, 3 drab beige'), 
 ('light fuchsia', '2 plaid lavender, 4 dull green, 2 plaid salmon'), 
 ('dull bronze', '3 bright magenta, 1 bright black, 2 wavy lime'), 
 ('light gold', '5 bright indigo'), 
 ('drab magenta', '5 faded fuchsia, 2 dim black, 5 dim crimson, 5 dotted fuchsia'), 
 ('mirrored lime', '2 mirrored white, 1 shiny gray'), 
 ('dim olive', '4 bright blue, 1 faded tomato'), 
 ('striped tan', '4 dark tomato, 4 mirrored coral, 2 mirrored lavender'), 
 ('muted coral', '4 pale salmon, 3 faded purple'), 
 ('striped violet', '4 dark gray, 3 posh coral, 2 striped turquoise, 4 bright fuchsia'), 
 ('clear plum', '3 bright cyan, 1 drab salmon, 2 vibrant brown'), 
 ('clear brown', '1 mirrored plum'), 
 ('light indigo', '4 drab blue, 5 mirrored chartreuse, 2 muted red, 2 dark beige'), 
 ('dim purple', '4 wavy teal'), 
 ('clear yellow', '4 clear maroon, 3 bright olive, 5 shiny gray, 2 bright orange'), 
 ('pale tomato', '2 dotted violet, 2 dark teal'), 
 ('bright teal', '2 shiny maroon, 2 muted indigo'), 
 ('pale plum', '5 posh gray, 3 shiny indigo, 3 wavy olive, 1 pale white'), 
 ('dark teal', '3 muted plum, 4 faded plum, 1 wavy bronze'), 
 ('vibrant crimson', '5 dark tomato, 2 dark white, 5 posh red'), 
 ('shiny aqua', '1 pale coral'), 
 ('dim chartreuse', '2 wavy teal, 5 mirrored black, 5 mirrored bronze, 4 muted lavender'), 
 ('drab beige', '2 faded coral, 5 muted tan, 5 plaid cyan'), 
 ('bright purple', '4 muted red, 5 wavy beige, 4 clear coral'), 
 ('striped black', '3 light red, 2 plaid chartreuse'), 
 ('striped chartreuse', '2 dotted gray, 2 wavy olive, 1 muted lavender'), 
 ('dull gold', '5 wavy olive, 2 posh plum, 4 shiny gold'), 
 ('striped lavender', '5 dim teal, 3 light blue'), 
 ('striped lime', '4 light black, 5 striped turquoise, 5 wavy cyan')


 drop table if exists #SplitInput
 select 
	id,
	sBag,
	sContent,
	case when value = 'no other' then sBag else trim( right(trim(value), len(value)-2)) end as bag,
	sbag as ContainedIn, 
	cast( case when value = 'no other' then 1 else left(trim(value), 1) end as int) as NumBagsInParent
 into #SplitInput
 from #test a
 cross apply string_split(sContent, ',')

 --select * from #SplitInput
 --order by NumBagsInParent




 ;WITH items AS (
    SELECT distinct sbag, ContainedIn
    , 0 AS Level
    , CAST(sbag AS VARCHAR(255)) AS Path
    FROM #SplitInput a
    WHERE a.ContainedIn not in (select b.bag from #SplitInput b)

    UNION ALL

    SELECT i.bag, i.ContainedIn
    , Level + 1
    , CAST(Path + '.' + CAST(i.bag AS VARCHAR(255)) AS VARCHAR(255))
    FROM #SplitInput i
    INNER JOIN items itms ON itms.sBag = i.ContainedIn
	where bag <> itms.ContainedIn
)

SELECT count(distinct value) FROM items 
cross apply string_split(left(path, len(path)-11), '.')
where sBag = 'shiny gold'


 ;WITH items AS (
    SELECT distinct sbag, ContainedIn
    , 0 AS Level
	, 1 as NumBags
	, 1 as NumBagsTotal
    , CAST(sbag AS VARCHAR(255)) AS Path
    FROM #SplitInput a
    WHERE a.sBag = 'shiny gold'

    UNION ALL

    SELECT i.bag, i.ContainedIn
    , Level + 1
	, i.NumBagsInParent
	, i.NumBagsInParent * NumBagsTotal
    , CAST(Path + '.' + CAST(i.bag AS VARCHAR(255)) AS VARCHAR(255))
    FROM #SplitInput i
    INNER JOIN items itms ON itms.sBag = i.ContainedIn
	where bag <> itms.ContainedIn
)

SELECT sum(NumBagsTotal) FROM items
where sbag <> ContainedIn

return















 ;WITH items AS (
    SELECT distinct sbag, ContainedIn
    , 0 AS Level
    , CAST(sbag AS VARCHAR(255)) AS Path
    FROM #SplitInput a
    WHERE a.ContainedIn not in (select b.bag from #SplitInput b)

    UNION ALL

    SELECT i.bag, i.ContainedIn
    , Level + 1
    , CAST(Path + '.' + CAST(i.bag AS VARCHAR(255)) AS VARCHAR(255))
    FROM #SplitInput i
    INNER JOIN items itms ON itms.sBag = i.ContainedIn
)

SELECT * FROM items ORDER BY Path


    SELECT 
		distinct sBag, ContainedIn
    FROM #SplitInput a
    WHERE a.ContainedIn not in (select b.bag from #SplitInput b)
	group by sBag, ContainedIn

	SELECT 
		distinct sBag
    FROM #SplitInput a
    WHERE sbag = ContainedIn

	select * from #SplitInput
	where sbag = 'bright beige'